# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-17 21:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20160406_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='new_created_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='menu',
            name='new_created_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AddField(
            model_name='menu',
            name='new_expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
