# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-17 21:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_auto_20171117_1545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='expiration_date',
        ),
    ]
