# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-17 21:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_auto_20171117_1555'),
    ]

    operations = [
		migrations.RenameField('Menu', 'new_created_date', 'created_date'),
		migrations.RenameField('Menu', 'new_expiration_date', 'expiration_date'),
		migrations.RenameField('Item', 'new_created_date', 'created_date')
    ]
